####################################################
#IR KITCHEN HOOD AUTOMATION
#################################################### 
#https://www.home-assistant.io/components/automation/
#/config/automation
#date: 04.05.2019

####################################################
# FAN CONTROL
####################################################

- alias: 'ir_kitchen_hood_set_fan_set'
  trigger:
    platform: state
    entity_id: input_number.ir_kitchen_hood_fan_speed
  action:
    service: python_script.ir_kitchen_hood_fan_control
    data_template:
      command: >-
        {% set to = trigger.to_state.state | int %}
        {% set from = trigger.from_state.state | int %}
        {% set diff = (from - to) | round(0) %}
        {% set slider = states('input_number.ir_kitchen_hood_fan_speed') | round(0) %}
        {% set step = (diff / 1) | round(0) %}
        {% if slider == 0 %}
          0
        {% elif slider == 1 %}
          6
        {% else %}
          {{step}}
        {% endif %}

####################################################
#                                                  #
#            END OF CONFIGURATION FILE             #
#                                                  #
####################################################
