####################################################
##  ENERGY COSTS TEMPLATES             
####################################################
####################################################
## TOTAL ENERGY COSTS + CUMULATIVE
####################################################
##
### ENERGY
##
- platform: template
  sensors:
    electrical_energy_vt_today:
      entity_id:
        - sensor.bathroom_washer_and_dryer_electrical_energy_tariff_vt
        - sensor.hallway_climate_electrical_energy_tariff_vt
        - sensor.childrensroom_electronics_electrical_energy_tariff_vt
      value_template: "{{ (states('sensor.bathroom_washer_and_dryer_electrical_energy_tariff_vt')|float + states('sensor.hallway_climate_electrical_energy_tariff_vt')|float + states('sensor.childrensroom_electronics_electrical_energy_tariff_vt')|float)|round(3) }}"
      unit_of_measurement: "kWh"
##
- platform: template
  sensors:
    electrical_energy_mt_today:
      entity_id:
        - sensor.bathroom_washer_and_dryer_electrical_energy_tariff_mt
        - sensor.hallway_climate_electrical_energy_tariff_mt
        - sensor.childrensroom_electronics_electrical_energy_tariff_mt
      value_template: "{{ (states('sensor.bathroom_washer_and_dryer_electrical_energy_tariff_mt')|float + states('sensor.hallway_climate_electrical_energy_tariff_mt')|float + states('sensor.childrensroom_electronics_electrical_energy_tariff_mt')|float)|round(3) }}"
      unit_of_measurement: "kWh"
##
- platform: template
  sensors:
    electrical_energy_today:
      entity_id:
        - sensor.electrical_energy_vt_today
        - sensor.electrical_energy_mt_today
      value_template: "{{ (states('sensor.electrical_energy_vt_today')|float + states('sensor.electrical_energy_mt_today')|float)|round(3) }}"
      unit_of_measurement: "kWh"
##
### COSTS
##
- platform: template
  sensors:
    electrical_energy_vt_cost_today:
      entity_id:
        - sensor.bathroom_washer_and_dryer_electrical_energy_vt_cost_today
        - sensor.hallway_climate_electrical_energy_vt_cost_today
        - sensor.childrensroom_electronics_energy_vt_cost_today
      value_template: "{{ ( states('sensor.bathroom_washer_and_dryer_electrical_energy_vt_cost_today')|float + states('sensor.hallway_climate_electrical_energy_vt_cost_today')|float + states('sensor.hallway_childrensroom_electronics_vt_cost_today')|float)|round(3) }}"
      unit_of_measurement: "EUR"
##
- platform: template
  sensors:
    electrical_energy_mt_cost_today:
      entity_id:
        - sensor.bathroom_washer_and_dryer_electrical_energy_mt_cost_today
        - sensor.hallway_climate_electrical_energy_mt_cost_today
        - sensor.childrensroom_electronics_energy_mt_cost_today
      value_template: "{{ ( states('sensor.bathroom_washer_and_dryer_electrical_energy_mt_cost_today')|float + states('sensor.hallway_climate_electrical_energy_mt_cost_today')|float + states('sensor.hallway_childrensroom_electronics_mt_cost_today')|float)|round(3) }}"
      unit_of_measurement: "EUR"
##
- platform: template
  sensors:
    electrical_energy_cost_today:
      entity_id:
        - sensor.bathroom_washer_and_dryer_electrical_energy_cost_today
        - sensor.hallway_climate_electrical_energy_cost_today
        - sensor.childrensroom_electronics_energy_cost_today
      value_template: "{{ ( states('sensor.bathroom_washer_and_dryer_electrical_energy_cost_today')|float + states('sensor.hallway_climate_electrical_energy_cost_today')|float + states('sensor.hallway_childrensroom_electronics_cost_today')|float)|round(3) }}"
      unit_of_measurement: "EUR"
##
### CUMULATIVE COSTS
##
- platform: template
  sensors:
    cumulative_energy_cost:
      friendly_name: 'Cumulative Energy Cost' #### for Lovelace display only. Calculations use the input_number.
      entity_id:
        - input_number.cumulative_energy_cost
      value_template: "{{ states('input_number.cumulative_energy_cost')|float|round(3) }}"
      unit_of_measurement: "EUR"
##
- platform: template
  sensors:
    last_reset:
      friendly_name: 'Last Reset' # Date the cumulative total cost was reset.
      entity_id:
        - input_datetime.last_reset
      value_template: "{{ states('input_datetime.last_reset') }}"
##
####################################################
## END
####################################################
